# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

resources:
- repo: self

variables:
  imageName: test
  tag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    displayName: Build uni-test Docker for SuperBench testing
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/test.dockerfile'
      repository: $(imageName)
      tags: |
        $(tag)
  - script: |
      ci_env=`bash <(curl -s https://codecov.io/env)`
      docker run $ci_env --entrypoint /bin/bash $(imageName):$(tag) -c 'bash <(curl -s https://codecov.io/bash)'
    displayName: Report coverage results
    env:
      CODECOV_TOKEN: $(codecovToken)
